### ISSUE TITLE
Question-1

### ISSUE THREAD

**Issue by Sagittarius-22** [Sagittarius-22/Question-1#1]
是不是在这里输入代码和问题描述就行

**Comment by Sagittarius-22** [comment]
![8c901c50c77ca591239063161c89053](https://user-images.githubusercontent.com/112104249/186714182-f9d8222d-4326-4cbe-b687-3b9770b1938d.jpg)
为什么23、24行代码调用的函数是fn2而不是fn1；以及在调用fn1的时候，fn2会一起被调用吗？或者是fn2会被放入到执行上下文栈吗？

**Comment by CocaColf** [comment]
这个问题主要涉及到以下几个知识点：

- 闭包
- 作用域
- js 垃圾回收机制

> 为什么23、24行代码调用的函数是fn2而不是fn1

因为 `var f = fn1()` 实际上可以理解为将 `fn1` 的执行结果赋值给 `f`，我们只关注 `fn1` 的返回值，它是 `fn2` ，所以实际上可以理解为 `f` 就是 `fn2`。所以说执行 `f` 时实际上就是执行的 `fn2`

> 在调用fn1的时候，fn2会一起被调用吗

不会。因为在 `fn1` 内部，根本没有 `fn2` 的调用，调用应该是 `fn2()` 这样

> 其他

1. 这里实际上是一个闭包的例子，`fn2` 是一个闭包，因为它访问了 `fn1` 内部的变量。说得专业一点就是 `fn2` 保持对 `fn1` 内部变量 `a` 的引用
2. `a` 为什么是累加的而不是每次调用保持是 2 这个结果？这里涉及到 `垃圾回收机制`。简单来讲就是 `fn2` 现在被赋值给了全局变量 `f`，全局变量只有在程序退出时才会被收回内存，所以说和 f 作用域相关的变量都不会被内存回收，所以 `a` 始终处于内存中，因此每次都可以在前一个值的基础上累加

**Comment by Sagittarius-22** [comment]
![微信截图_20220829100706](https://user-images.githubusercontent.com/112104249/187109033-fca6a234-e2b1-4661-83f4-cc0c12a63213.png)
在01里面引入上面02文件夹里面的文件怎么引？ 因为层级多， ../ 的方式没有用 @CocaColf

**Comment by Sagittarius-22** [comment]
js里面 结尾是不是可以全部不写 ； 号，当然特殊情况除外 @CocaColf

**Comment by CocaColf** [comment]
> ![微信截图_20220829100706](https://user-images.githubusercontent.com/112104249/187109033-fca6a234-e2b1-4661-83f4-cc0c12a63213.png) 在01里面引入上面02文件夹里面的文件怎么引？ 因为层级多， ../ 的方式没有用 @CocaColf

引入方式就是通过这种路径的方式引用的，如果不行就拷贝一份来用吧。

**Comment by CocaColf** [comment]
> js里面 结尾是不是可以全部不写 ； 号，当然特殊情况除外 @CocaColf

是的，可以不用写，js 有机制，所以写和不写就是一个个人习惯问题了。我个人是习惯写的，这样切换到其他语言不会出现不习惯写分号的问题。

**Comment by Sagittarius-22** [comment]
![image](https://user-images.githubusercontent.com/112104249/187115956-9a015d30-2e3f-4380-97cb-4296e6b4f96f.png)
![image](https://user-images.githubusercontent.com/112104249/187116144-672f88d4-d315-4dac-a7c6-50b23095ced7.png)

@CocaColf 这行代码在这里报错，目的我想通过js动态设置一个元素的宽度，但是不知道错在哪里

**Comment by Sagittarius-22** [comment]
![111](https://user-images.githubusercontent.com/112104249/187116285-425f26b8-6268-49ba-9999-84ba2c8aef55.png)

![微信截图_20220829111813](https://user-images.githubusercontent.com/112104249/187116266-9ed6aaee-90d4-4eb9-9c2c-56f1dc4f99ee.png)
这行代码在这里报错，目的我想通过js动态设置一个元素的宽度，但是不知道错在哪里 @CocaColf

**Comment by Sagittarius-22** [comment]
我发现如果html结构里面元素不用class属性，用id属性，然后上面的js代码改成getElementById，就没问题了,为什么呢

**Comment by CocaColf** [comment]
> ![111](https://user-images.githubusercontent.com/112104249/187116285-425f26b8-6268-49ba-9999-84ba2c8aef55.png)
> 
> ![微信截图_20220829111813](https://user-images.githubusercontent.com/112104249/187116266-9ed6aaee-90d4-4eb9-9c2c-56f1dc4f99ee.png) 这行代码在这里报错，目的我想通过js动态设置一个元素的宽度，但是不知道错在哪里 @CocaColf

1. 因为页面里 class 名称是可以重复定义的，而 id 才是唯一的。所以使用 `getElementByClassName` 获取到的是一个数组。因此这个设置代码不会生效
2. 以后一个问题单独开一个 issue，解决后修改 issue 状态 为 closed
